---
title: "Beachhead Assignment Approach"
author: "Mubin Ejaz"
description: Data 607, Beachead Assignment
format: html
editor: visual
---

## The Problem: 

There is a common understanding that factors such as pollution, traffic, industry waste and etc affect air quality and environment.

It would be interesting to see how airquality has been affected for the last very many years and what factors have most affect on it. I will only be focusing on New York.

## Airquality Dataset (s)

For the beachhead assignment, I have chosen outdoor air quality data from EPA.gov (it queries dataset csv from AirNow).

## Possible Challenges

I would like to see how the Ozone's value has changed over the period of last some years, and how that has affected air quality in New York.

I downloaded the csv from [Download Daily Data \| US EPA](https://www.epa.gov/outdoor-air-quality-data/download-daily-data) (air quality summary statistics for criteria pollutants by monitor for new york)

The EPA.gov website allows you to download various pollutant and corresponding daily data. I would be experimenting with both data sets.

Considering this will be the first time I'll be using R, the learning curve maybe a challenge. Taking a small enough chunk of the data that shows a meaningful conclusion might be another challenge.

```{r}
library(tidyverse)

AirData<-read.csv("ad_viz_plotval_data.csv")
glimpse(AirData)

AirData %>%
mutate(Date = as.Date(Date, format = "%m/%d/%Y")) %>%
filter(Date >= "2026-09-01") %>% 
ggplot(aes(x=Date, y=Daily.Max.8.hour.Ozone.Concentration))+geom_line(color="blue") + labs(title="Daily Ozone Concentration this Year in New York")
```

## Possible Solution: 

I would be sticking with a few datasets for this assignment, but experimenting with dataset I download from EPA.gov website. I'll try to compare different polutants and ozone data. \

------------------------------------------------------------------------

## AI Usage: 

ChatGPT, GPT-5.6 Luna.

### Prompt: 

[I've loaded a csv file in variable AirData (got the data from EPA.gov. Is this correct way to filter out last few months of dates ? filter(AirData\$date\>="2026-05-01") %\>% ggplot(data=AirData, mapping=aes(x=Date, y=Daily.Max.8.hour.Ozone.Concentration))+geom_line(color="blue") + labs(title="Daily Ozone Concentration this Year in New York")]{.underline}

###  Response: 

You're very close — there are just a couple of things to fix.

[1. Your `filter()` is correct in principle]{.underline}

[If your date column is actually called `date` and is stored as a proper Date:]{.underline}

```         
filter(AirData, date >= "2026-05-01")
```

[or in a pipe:]{.underline}

```         
AirData %>%   filter(date >= "2026-05-01")
```

[2. The main issue is that your filtered data isn't being passed to `ggplot()`]{.underline}

[You currently have:]{.underline}

```         
filter(AirData$date >= "2026-05-01") %>%   ggplot(data = AirData, mapping = aes(...))
```

[The `ggplot()` is then told to use **AirData again**, so it ignores the filtered result.]{.underline}

[Instead:]{.underline}

```         
AirData %>%   filter(date >= "2026-05-01") %>%   ggplot(aes(x = date, y = Daily.Max.8.hour.Ozone.Concentration)) +   geom_line(color = "blue") +   labs(title = "Daily Ozone Concentration this Year in New York")
```

After learning how to actually filter, I was able to also mutate the Date to be used as an int instead of char.
